development:
  adapter: postgresql
  encoding: unicode
  database: crashbox_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: crashbox_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: crashbox_production
  pool: 5
  username:
  password:
